---
- hosts: all
  tags: always
  become: true
  gather_facts: no
  tasks:

    - name: Importing User Information
      ansible.builtin.include_vars: userInfo.yml

- hosts: jsspeedtest
  tags: speed
  become: true
  gather_facts: no
  ignore_unreachable: no
  tasks:

  - name: Importing Speedtest's VMs Variables
    ansible.builtin.include_vars: xcp_speed.yml

  - name: Creating Speedtest Virtual Machine
    ansible.builtin.import_role:
      name: createVM

- hosts: jsspeedtest
  tags: speed
  become: true
  gather_facts: yes
  tasks:

  - name: Building Speedtest Server
    ansible.builtin.import_role:
      name: speedtest

- hosts: jsstreaming
  tags: media
  become: true
  gather_facts: no
  ignore_unreachable: no
  tasks:

    - name: Importing Jellyfin's VM Variables
      ansible.builtin.include_vars: xcp_jellyfin.yml

    - name: Creating Jellyfin Virtual Machine
      ansible.builtin.import_role:
        name: createVM

- hosts: jsstreaming
  tags: media
  become: true
  gather_facts: yes
  tasks:

  - name: Setting Up Jellyfin Server
    ansible.builtin.import_role:
      name: jellyfin

- hosts: jsgit
  tags: git
  become: true
  gather_facts: no
  tasks:

  - name: Importing Gitea's VM Variables
    ansible.builtin.include_vars: xcp_git.yml

  - name: Creating Gitea Virtual Machine
    ansible.builtin.import_role:
      name: createVM

- hosts: jsgit
  tags: git
  become: true
  gather_facts: yes
  tasks:

  - name: Setting Up Gitea Server
    ansible.builtin.import_role:
      name: gitea

- hosts: jsdns2
  tags: dns
  become: true
  gather_facts: no
  tasks:

  - name: Importing Pi-Hole's VM Variables
    ansible.builtin.include_vars:
    name: xcp_dns.yml

  - name: Create Pi-Hole Virtual Machine
    ansible.builtin.include_role:
      name: createVM

- hosts: jsdns2
  tags: dns
  become: true
  gather_facts: yes

    - name: Setting Up Pi-Hole Server
      ansible.builtin.import_role:
        name: dns

#- hosts: jsunifi2
#  tags: unifi
#  become: true
#  gather_facts: no
#  tasks:

#  - name: Importing Unifi's VM Varialbes
#    ansible.builtin.include_vars: xcp_unifi.yml

#  - ansible.builtin.import_role:
#      name: createVM

#- hosts: jsunifi2
#  tags: unifi
#  become: true
#  gather_facts: yes
#  tasks:

#  - name: Setting Up Unifi Controller
#    ansible.builtin.import_role:
#      name: unifi
