# - name: Importing Gitea Variables
#  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: Removing CD-ROM from Sources
  ansible.builtin.apt_repository:
    repo: deb cdrom
    state: absent

- name: Updating Gitea VM
  ansible.builtin.import_role:
    name: updateServers
