- name: Update all packages (Debian based)
#  tags: servers
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  when:
    - ansible_os_family == "Debian"

- name: Update all packages (Fedora based)
#  tags: servers
  ansible.builtin.dnf:
    name: "*"
    update_only: yes
    update_cache: yes
    state: latest
  when:
    - ansible_os_family == "RedHat"

- name: Auto Removing Uneeded Apps
  ansible.builtin.package:
    autoremove: yes

- name: Checking if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Rebooting the server
  tags: servers
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true
